CodingCowboys10/kmai

actions/script.py
=> CC-37 Fix script.py (#36)

2-RTB/Piano_di_qualifica/frontespizio.tex, 2-RTB/Piano_di_qualifica/log.tex, 2-RTB/Piano_di_qualifica/pianodiqualita.tex
Nella review scrivere: "Stesura sezione \ref{sec:qualityprod}." grazie.
E per favore, quando accettate non fate squash and merge subito. Che probabilmente il log automatico sbaglia. Grazie!
=> CC-69 Add metriche per prodotti

2-RTB/poc/src/app/chat/llm_menu/llm_menu_components.tsx
Bottoni che completano il cc-76
=> CC-78 Aggiunta dei bottoni per selezione LLM

2-RTB/Piano_di_qualifica/frontespizio.tex, 2-RTB/Piano_di_qualifica/log.tex, 2-RTB/Piano_di_qualifica/pianodiqualita.tex
=> Update Test Sistema

2-RTB/Glossario/letteraD.tex, 2-RTB/Glossario/letteraW.tex
Scrivere "Aggiunta di alcuni termini."
=> Cc 135 aggiunta docker e whisper

2-RTB/Piano_di_qualifica/frontespizio.tex, 2-RTB/Piano_di_qualifica/log.tex, 2-RTB/Piano_di_qualifica/pianodiqualita.tex
Aggiunta la sezione Piano di qualità -> Introduzione.
Scrivere: "Stesura sezione \ref{sec:qualityintro}."
=> Aggiunta sezione Introduzione 2

2-RTB/Analisi_dei_requisiti/frontespizio.tex, 2-RTB/Analisi_dei_requisiti/log.tex, 2-RTB/Analisi_dei_requisiti/requisiti.tex
Sulla review scrivere Aggiornato capitolo \ref{sec:requisiti}
=> Aggiornamento requisiti

2-RTB/Norme_di_progetto/frontespizio.tex, 2-RTB/Norme_di_progetto/log.tex, 2-RTB/Norme_di_progetto/processiPrimari.tex
Scrivere "Aggiornamento strumenti nella sezione \ref{sec:sviluppo}."
=> aggiunta di SQLite

2-RTB/Piano_di_qualifica/frontespizio.tex, 2-RTB/Piano_di_qualifica/log.tex, 2-RTB/Piano_di_qualifica/pianodiqualita.tex
Scrivere Aggiornata sezione \ref{sec:test}
=> Aggiornamento test di sistema

2-RTB/Glossario/frontespizio.tex, 2-RTB/Glossario/letteraM.tex, 2-RTB/Glossario/log.tex
Scrivere: "Aggiunta di alcuni termini."
=> Cc-146 aggiunta minio

2-RTB/Analisi_dei_requisiti/frontespizio.tex, 2-RTB/Analisi_dei_requisiti/log.tex, 2-RTB/Analisi_dei_requisiti/requisiti.tex
Aggiunti requisiti per docker e minIO, fix requisiti di sistema (ora si capisce che docker è necessario), aggiornamento tabella riepilogo, fixato log rotto
Scrivere in log Aggiornamento capitolo \ref{sec:requisiti}.
=> Fix log e aggiornamento requisiti

2-RTB/Documentazione_esterna/Glossario/frontespizio.tex, 2-RTB/Documentazione_esterna/Glossario/letteraO.tex, 2-RTB/Documentazione_esterna/Glossario/letteraP.tex, 2-RTB/Documentazione_esterna/Glossario/log.tex
Scrivere: "Aggiunta di alcuni termini."
questi 2 termini vanno in glossario 1.0 o nel 2.0?
=> Cc 162 aggiunta di orm e prisma

2-RTB/Documentazione_esterna/Piano_di_qualifica/frontespizio.tex, 2-RTB/Documentazione_esterna/Piano_di_qualifica/log.tex, 2-RTB/Documentazione_esterna/Piano_di_qualifica/pianodiqualita.tex
Scrivere: Aggiornamento sezione \ref{sec:test}.
=> Aggiornamento test

3-PB/Documentazione_interna/Norme_di_progetto/frontespizio.tex, 3-PB/Documentazione_interna/Norme_di_progetto/log.tex, 3-PB/Documentazione_interna/Norme_di_progetto/processiDiSupporto.tex
Aggiornamento sezione \ref{sec:verificheispettive}.
=> Aggiunta sezione PB

3-PB/Documentazione_interna/Norme_di_progetto/frontespizio.tex, 3-PB/Documentazione_interna/Norme_di_progetto/log.tex, 3-PB/Documentazione_interna/Norme_di_progetto/processiDiSupporto.tex
Aggiornata sezione \ref{sec:documentazione}.
=> Aggiornamento sezione documentazione

3-PB/Documentazione_interna/Norme_di_progetto/frontespizio.tex, 3-PB/Documentazione_interna/Norme_di_progetto/log.tex, 3-PB/Documentazione_interna/Norme_di_progetto/processiDiSupporto.tex, 3-PB/Documentazione_interna/Norme_di_progetto/processiPrimari.tex
aggiunta riferimenti a 3-pb e 3-pb/MVP, aggiunta specifica architetturale
( Aggiornamento sezione \ref{sec:sviluppo} e \ref{sec:gestconf}. )
=> Cc 185 aggiornamento processo sviluppo

3-PB/Documentazione_esterna/Specifica_architetturale/introduzione.tex, 3-PB/Documentazione_esterna/Specifica_architetturale/log.tex, 3-PB/Documentazione_esterna/Specifica_architetturale/tecnologie.tex
Stesura sezione \ref{cap:tech}.
=> CC-183 stesura sezione tecnologie

3-PB/mvp/src/components/documents/dataTable.tsx, 3-PB/mvp/src/components/documents/docContent.tsx, 3-PB/mvp/src/components/documents/docForm.tsx, 3-PB/mvp/src/controllers/document/GetDocumentsController.ts
Aggiunta barra di filtro per data.
Fixati formati di data e size, che causavano errore nel componente DataTable.
Aggiunta chiamata al controller per l'upload, quando si clicca sul bottone Invia. Implementato in modo che una volta che clicchi invia, se vuoi per qualche motivo reinviare quel file devi reselezionarlo.
=> Cc 228 ricerca documenti per data + fix

3-PB/Documentazione_interna/Norme_di_progetto/frontespizio.tex, 3-PB/Documentazione_interna/Norme_di_progetto/log.tex, 3-PB/Documentazione_interna/Norme_di_progetto/processiDiSupporto.tex, 3-PB/Documentazione_interna/Norme_di_progetto/processiPrimari.tex
Scrivere nel log "Aggiornamento sezione \ref{sec:sviluppo}, \ref{sec:verifica} e {sec:revisionicliente}."
Modificate apportate ai processi:
1. Revisioni congiunte con il cliente
--> aggiunto riferimento ad azioni da intraprendere per buona riuscita degli incontri;
2. Verifica
--> aggiunto riferimento ai test come parametro da controllare nella verifica dei prodotti software;
3. Sviluppo
--> aggiunto riferimento a test di integrazione (attività di progettazione), di unità (attività di progettazione di dettaglio) e alla stesura del manuale utente (ultima attività del processo). Cambiato anche SQLite in Postrges negli strumenti del processo.
=> Update Sviluppo Verifica Rev.Con.Cliente

3-PB/Documentazione_esterna/Specifica_architetturale/archback.tex, 3-PB/Documentazione_esterna/Specifica_architetturale/ccdoc.sty, 3-PB/Documentazione_esterna/Specifica_architetturale/frontespizio.tex, 3-PB/Documentazione_esterna/Specifica_architetturale/log.tex
Stesura sezione \ref{subsec:serveractions}.
=> Cc 261 stesura server actions

3-PB/Documentazione_esterna/Piano_di_qualifica/frontespizio.tex, 3-PB/Documentazione_esterna/Piano_di_qualifica/log.tex, 3-PB/Documentazione_esterna/Piano_di_qualifica/pianodiqualita.tex
Scrivere per il log "Aggiornamento sezione \ref{sec:test}."
=> aggiornamento test di unità

3-PB/Documentazione_interna/Norme_di_progetto/frontespizio.tex, 3-PB/Documentazione_interna/Norme_di_progetto/introduzione.tex, 3-PB/Documentazione_interna/Norme_di_progetto/log.tex, 3-PB/Documentazione_interna/Norme_di_progetto/processiPrimari.tex
Aggiornamento sezione \ref{sec:sviluppo}.
=> Cc 283 aggiornamento processo sviluppo

actions/gloss.py
=> fix action gloss

3-PB/Documentazione_esterna/Piano_di_qualifica/frontespizio.tex, 3-PB/Documentazione_esterna/Piano_di_qualifica/log.tex, 3-PB/Documentazione_esterna/Piano_di_qualifica/pianodiqualita.tex
"Aggiornamento sezione \ref{sec:test}"
=> Cc 289 conclusione test di unità

3-PB/Documentazione_esterna/Glossario/frontespizio.tex, 3-PB/Documentazione_esterna/Glossario/letteraC.tex, 3-PB/Documentazione_esterna/Glossario/letteraD.tex, 3-PB/Documentazione_esterna/Glossario/letteraR.tex, 3-PB/Documentazione_esterna/Glossario/letteraU.tex, 3-PB/Documentazione_esterna/Glossario/log.tex
"Aggiunta di alcuni termini."
In particolare:
- CA
- Clean
- Componente
- Controller
- CSR
- Data source
- Database
- Dependency Injection
- Docker Compose
- Repository (aggiunto quando in riferimento a programmazione)
- Use case (aggiunto quando in riferimento a programmazione)
Al primo verificatore che fa un change request e non lo approva subito, lo spiezo (scherzo)
=> CC-290 Aggiornamento finale glossario

3-PB/Documentazione_esterna/Piano_di_progetto/frontespizio.tex, 3-PB/Documentazione_esterna/Piano_di_progetto/log.tex, 3-PB/Documentazione_esterna/Piano_di_progetto/rischi.tex
"Aggiornamento capitolo \ref{chap:rischi}."
=> CC-284 Aggiornamento rischi

3-PB/Documentazione_esterna/Specifica_architetturale/archback.tex, 3-PB/Documentazione_esterna/Specifica_architetturale/frontespizio.tex, 3-PB/Documentazione_esterna/Specifica_architetturale/log.tex
Stesura sezione \ref{subsec:api}.
=> CC-275 Stesura API chat

3-PB/Documentazione_esterna/Manuale_utente/ccdoc.sty, 3-PB/Documentazione_esterna/Manuale_utente/frontespizio.tex, 3-PB/Documentazione_esterna/Manuale_utente/installazione.tex, 3-PB/Documentazione_esterna/Manuale_utente/log.tex
scrivere: "Stesura sezione \ref{cap:Inst}."
=> Cc 265 installazione

3-PB/Documentazione_esterna/Manuale_utente/frontespizio.tex, 3-PB/Documentazione_esterna/Manuale_utente/istruzioni.tex, 3-PB/Documentazione_esterna/Manuale_utente/log.tex
=> Cc 295 aggiornamento istruzioni documenti

.idea/.gitignore, .idea/inspectionProfiles/Project_Default.xml, .idea/vcs.xml, 2-RTB/poc/check-services.mjs, 2-RTB/poc/src/utils/chat_utils.ts, 3-PB/Documentazione_esterna/Piano_di_qualifica/frontespizio.tex, 3-PB/Documentazione_esterna/Piano_di_qualifica/log.tex, 3-PB/Documentazione_esterna/Piano_di_qualifica/pianodiqualita.tex
Aggiornamento sezione \ref{sec:test}.
=> Cc 296 aggiornamento test accettazione

3-PB/Documentazione_esterna/Manuale_utente/frontespizio.tex, 3-PB/Documentazione_esterna/Manuale_utente/introduzione.tex, 3-PB/Documentazione_esterna/Manuale_utente/log.tex
Aggiornamento sezione \ref{cap:intro}.
=> add utilizzatori
